///////////////////////////////////////////////////////////
//  CompteBancaire.cs
//  Implementation of the Class CompteBancaire
//  Generated by Enterprise Architect
//  Created on:      22-juin-2023 16:08:46
//  Original author: SCsaszar
///////////////////////////////////////////////////////////




public class CompteBancaire {

	private int decouvertAutorise;
	private string nomProprietaire;
	private int numerUniqueIdentification;
	private int solde;

	public CompteBancaire(){

	}

	~CompteBancaire(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="CompteBancaire2"></param>
	public bool Comparer(CompteBancaire CompteBancaire2){

		return false;
	}

	public void Compte(){

	}

	/// 
	/// <param name="numeroUniqueIdentification"></param>
	/// <param name="nomProprietaire"></param>
	/// <param name="solde"></param>
	/// <param name="decouvertAutorise"></param>
	public void Compte(int numeroUniqueIdentification, string nomProprietaire, decimal solde, int decouvertAutorise){

	}

	/// 
	/// <param name="montantCredit"></param>
	public void Crediter(decimal montantCredit){

	}

	/// 
	/// <param name="montantDebit"></param>
	public bool Debiter(decimal montantDebit){

		return false;
	}

	public string ToString(){

		return "";
	}

	/// 
	/// <param name="montantTransfer"></param>
	/// <param name="compteBancaireDestinataire"></param>
	public bool Transferer(int montantTransfer, CompteBancaire compteBancaireDestinataire){

		return false;
	}

}//end CompteBancaire